const mongoose = require('mongoose');

const setSchema = new mongoose.Schema({
  reps: { type: Number, required: true },
  weight: { type: Number, required: true },
  // Optional fields
  distance: { type: Number },
  duration: { type: Number }, // in seconds
  isCompleted: { type: Boolean, default: true }
}, { _id: false });

const performedExerciseSchema = new mongoose.Schema({
  exercise: { type: mongoose.Schema.Types.ObjectId, ref: 'Exercise', required: true },
  sets: [setSchema],
  notes: { type: String },
}, { _id: false });

const workoutSessionSchema = new mongoose.Schema({
  // UUID generated by the client to uniquely identify the session across devices
  clientId: { type: String, required: true, unique: true }, 
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  startTime: { type: Date, required: true },
  endTime: { type: Date },
  notes: { type: String },
  performedExercises: [performedExerciseSchema],
  // This is crucial for conflict resolution (Last Write Wins)
  lastModifiedAt: { type: Date, required: true },
}, { timestamps: true }); // createdAt and updatedAt from Mongoose

const WorkoutSession = mongoose.model('WorkoutSession', workoutSessionSchema);
module.exports = WorkoutSession;